package service;

public class AIService {

    public String generateLesson(String prompt) {

        if (prompt == null || prompt.isBlank()) {
            return "No prompt provided.";
        }

        StringBuilder sb = new StringBuilder();

        sb.append("# AI Generated Lesson\n\n");
        sb.append("## Introduction\n");
        sb.append("This lesson is generated based on the following request:\n\n");
        sb.append(prompt).append("\n\n");

        sb.append("## Main Concepts\n");
        sb.append("- Explain the topic clearly.\n");
        sb.append("- Provide examples.\n");
        sb.append("- Include best practices.\n");
        sb.append("- Add a summary section.\n\n");

        sb.append("## Example\n");
        sb.append("Sample explanation generated by AI.\n\n");

        sb.append("## Summary\n");
        sb.append("This content can be reviewed and edited by the SME before publishing.");

        return sb.toString();
    }

    public String generateSummary(String extractedText) {

        if (extractedText == null || extractedText.isBlank()) {
            return "No text extracted.";
        }

        String text = extractedText.length() > 1000
                ? extractedText.substring(0, 1000)
                : extractedText;

        return "# Lesson Summary\n\n"
                + "## Key Points\n"
                + text
                + "\n\n## Conclusion\nReview and refine this draft before publishing.";
    }
}

